
{{- range .Values.microservices }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .app_name }}-depl
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ .app_name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .app_name }}
  template:
    metadata:
      labels:
        app: {{ .app_name }}
    spec:
      containers:
      - name: {{ .app_name }}-container
        image: {{ .image.repo }}:{{ .image.tag }}
        imagePullPolicy: Always
        command: [{{ .app_command | quote }}]
        args: [{{ .app_args | quote }}]

        ports:
        {{- range .ports }}
        - containerPort: {{ .number }}
        {{- end }}
        
        env:
        {{- range $.Values.global.config_env }}
        - name: {{ . }}
          valueFrom:
            configMapKeyRef:
              name: thuso-config
              key: {{ . }}
        {{- end }}

        {{- range .plain_env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}

        {{- range $.Values.global.secret_env }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: thuso-secret
              key: {{ . }}
        {{- end }}

        {{- range .secret_env }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: thuso-secret
              key: {{ . }}
        {{- end }}

        livenessProbe:
          httpGet:
            path: {{ .health.path }}
            port: {{ .health.port }}
          initialDelaySeconds: 60
          periodSeconds: 120
          timeoutSeconds: 15
          failureThreshold: 2
          successThreshold: 1
        
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .app_name }}-service
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{ .app_name }}
  ports:
  {{- range .ports }}
  - protocol: TCP
    {{- if .name }}
    name: {{ .name }}
    {{- end }}
    port: {{ .number }}
    targetPort: {{ .number }}
  {{- end }}

---

{{- end }}